services:

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build: . # build l'image du dockerfile local
    env_file:
      - .env
    command: uvicorn src.main:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "5000:5000"
    volumes:
      - ./project:/app/project
      - ./uploads:/app/uploads  # bind mount: un seul dossier uploads à la racine du repo
    depends_on:
      - redis

  worker:
    build: .
    env_file:
      - .env
    command: celery -A src.infrastructure.celery.celery_app worker --loglevel=info
    volumes:
      - ./project:/app/project
      - ./uploads:/app/uploads  # bind mount: un seul dossier uploads à la racine du repo
    depends_on:
      - redis

  flower:
    build: .
    env_file:
      - .env
    command: celery -A src.infrastructure.celery.celery_app flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - worker
