apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: backtobasics
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: backtobasics
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          args: ["redis-server", "--save", "", "--appendonly", "no"]
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
