apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: backtobasics
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: backtobasics
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
